web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
        - .:/online
    ports:
        - "8001:8001"
    links:
        - db

db:
    image: postgres:9.4
    environment:
        POSTGRES_PASSWORD: postgres
